### ISSUE TITLE
💡 Instead of using `js-yaml`, do a string replace instead

### ISSUE THREAD

**Issue by gr2m** [oscard0m/octoherd-script-update-action-version-in-workflows#2]
**What’s missing?**

Update the YAML files without removing comments or changing formatting

**Why?**

[As mentioned in the README](https://github.com/oscard0m/octoherd-script-update-action-version-in-workflows/tree/a8b0adf545bff7c5543281316fefcb92aa42826f#caveats), comments are currently being removed as the YAML code is parsed and then re-generated using `js-yaml`.

I think for this action it might suffice to use `regex` to find an replace versions for used actions, as the changes are contained to a small part of a single line. 

Let me know what you think

**Alternatives you tried**

🤷🏼

**Comment by oscard0m** [comment]
Sorry I missed this issue in my GitHub inbox.

Yes, it has totally sense. I will work on it later today.
